// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/films/[slug].ts";
import * as $1 from "./routes/api/films/index.ts";
import * as $2 from "./routes/api/index.ts";
import * as $3 from "./routes/api/locations/[slug].ts";
import * as $4 from "./routes/api/locations/index.ts";
import * as $5 from "./routes/api/people/[slug].ts";
import * as $6 from "./routes/api/people/index.ts";
import * as $7 from "./routes/api/species/[slug].ts";
import * as $8 from "./routes/api/species/index.ts";
import * as $9 from "./routes/api/vehicles/[slug].ts";
import * as $10 from "./routes/api/vehicles/index.ts";
import * as $11 from "./routes/index.tsx";

const manifest = {
  routes: {
    "./routes/api/films/[slug].ts": $0,
    "./routes/api/films/index.ts": $1,
    "./routes/api/index.ts": $2,
    "./routes/api/locations/[slug].ts": $3,
    "./routes/api/locations/index.ts": $4,
    "./routes/api/people/[slug].ts": $5,
    "./routes/api/people/index.ts": $6,
    "./routes/api/species/[slug].ts": $7,
    "./routes/api/species/index.ts": $8,
    "./routes/api/vehicles/[slug].ts": $9,
    "./routes/api/vehicles/index.ts": $10,
    "./routes/index.tsx": $11,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
